# 1. Use an existing docker image as a base
FROM alpine

# 2. Download and install dependencies
RUN apk add --update redis

# 3. Tell the image what to do when it starts as a container
CMD ["redis-server"]